### PR TITLE
Update for Copilot Free

### PR DESCRIPTION
**Pull request by chriswblake**
### Summary

Github just released announced Copilot Free.

### Changes

- Replace Copilot trial prerequisite with Copilot Free.
- Update references as the end to point to updated Docs.

### CODE REVIEW

**Review by camihmerhar — APPROVED** [review]

**Review by a-a-ron — APPROVED** [review]

**Comment by bananacute** [comment]
what is the passvord

**Comment by milestone65** [comment]
Milestone

**Comment by milestone65** [comment]
😊Milestone

**Comment by milestone65** [comment]
YjBUcSAL8TC

**Comment by nisho12u8** [comment]
fris

**Review by CosmicJesterX — COMMENTED** [review]
Started on another walkthru

**Review by CosmicJesterX — COMMENTED** [review]
Copilot business

**Comment by manikanta0309** [comment]
### 3w33

**Pull request merged**
